apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: kafka-app
    component: producer
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.producer.service.port }}
      targetPort: 3000
  selector:
    app: kafka-app
    component: producer
